### ISSUE TITLE
Import error after pyinstaller

### ISSUE THREAD

**Issue by Anniywell** [boppreh/keyboard#133]
```
  File "my_code.py", line 4, in <module>
    import keyboard
  File "c:\miniconda3\envs\x86\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module

    exec(bytecode, module.__dict__)
  File "site-packages\keyboard\__init__.py", line 126, in <module>
  File "importlib\__init__.py", line 109, in import_module
ImportError: No module named 'keyboard._winkeyboard'
```

**Comment by 2press** [comment]
You have to add an hidden import for PyInstaller:

`hiddenimports=['mykeyboard._winkeyboard']`

**Comment by boppreh** [comment]
What's the best practices around pyinstaller? Should `_winkeyboard` be named something else to be included automatically?

**Comment by 2press** [comment]
I don't know what is the best practice with pyinstaller. The problem is the use of importlib and the fact that it effectively hides the import from pyinstaller: https://github.com/boppreh/keyboard/blob/14cd6f53ef143b61bf23caedf8fb08bb4ad392bf/keyboard/__init__.py#L120-L127
 
The previous if-else-import chain was fully compatible with pyinstaller: 
https://github.com/boppreh/keyboard/commit/574f2599f22941223c4915dc44b0fe3f944101ce#diff-78144a085fc983d74768166c57ad6c89

Is there any reason why we can't go back to this?

**Comment by boppreh** [comment]
Ah, so PyInstaller is probably parsing the source code to find imports. No, there's no reason why we cannot go back. I'll revert the change as soon as I get home.

**Comment by ivanhercaz** [comment]
Hi,
I tried to use this module but I get this error too, ImportError after install. The traceback:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-f0d8a51b726e> in <module>()
----> 1 import keyboard

ImportError: No module named 'keyboard'
```
The same without IPython.

Regards,
Iván

**Comment by CrafterFlanceBOOM** [comment]
Hello,
I got an error yesterday. I tried deleting the keyboard folder and then install it again with pip, 
but it does not  even work still. I also got Visual Studio 2017 and I think that's problem.
Traceback:

C:\Users\brand\Desktop\VirusShooter>"Virus Shooter.py"
Traceback (most recent call last):
  File "C:\Users\brand\Desktop\VirusShooter\Virus Shooter.py", line 1, in <module>
    import keyboard
ImportError: No module named keyboard
