### ISSUE TITLE
[MacOS] [keyboard-0.13.1] ModuleNotFoundError: No module named 'Quartz'

### ISSUE THREAD

**Issue by jakubczaplicki** [boppreh/keyboard#146]
Issue #136 was closed, but I am afraid the issue still exist in v.0.13.1:  

```
$ python3 -m venv venv_keyboard

$ source venv_keyboard/bin/activate

$ pip install keyboard
Collecting keyboard
  Downloading keyboard-0.13.1-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 722kB/s 
Installing collected packages: keyboard
Successfully installed keyboard-0.13.1
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(venv_keyboard) $ python
Python 3.6.4 (default, Mar  9 2018, 23:15:03) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import keyboard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jakubczaplicki/PycharmProjects/venv_keyboard/lib/python3.6/site-packages/keyboard/__init__.py", line 124, in <module>
    from. import _darwinkeyboard as _os_keyboard
  File "/Users/jakubczaplicki/PycharmProjects/venv_keyboard/lib/python3.6/site-packages/keyboard/_darwinkeyboard.py", line 3, in <module>
    import Quartz
ModuleNotFoundError: No module named 'Quartz'
```

**Comment by boppreh** [comment]
I've reopened #136 to keep the issue history.
