### ISSUE TITLE
Exception with Python 3.5.3 64 bit and pyinstaller

### ISSUE THREAD

**Issue by DungFu** [boppreh/keyboard#157]
When using keyboard with python 3.5.3 64 bit and running inside of pyinstaller, this error is returned:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "site-packages\keyboard\__init__.py", line 296, in listen
  File "site-packages\keyboard\_winkeyboard.py", line 562, in listen
  File "site-packages\keyboard\_winkeyboard.py", line 555, in prepare_intercept
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert
```

I found a couple of other issues on other projects describing the same issue:
https://github.com/rene-aguirre/pywinusb/issues/30
https://github.com/jaraco/jaraco.windows/issues/7
https://stackoverflow.com/questions/44163105/python-3-5-1-amd64-ctypes-argumenterror-argument-1-class-overflowerror
https://bitbucket.org/pyglet/pyglet/issues/147/ctypesargumenterror-argument-4-int-too

Not sure exactly how to solve this for keyboard, but I am using 0.13.1. This error does not appear for me when I force using 32 bit Python in pyinstaller. I also only see the error inside of pyinstaller, not when just running a project normally with Python 3.5.3 64 bit.

**Comment by boppreh** [comment]
Thank you for the in-depth report, I'm working on it.

**Comment by GbeTech** [comment]
Having the exact same issue. Any temporary workaround maybe, just to get the exe going?

**Comment by taylorsmurphy** [comment]
I figured out the easy workaround finally, @GbeTech this should work for you too.

in keyboard\_winkeyboard.py line 555 replace 
`    keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, (GetModuleHandleW(None), None)`
with
`    keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, ctypes.c_ulonglong(GetModuleHandleW(None)), None)`

**Comment by Searinox** [comment]
Can confirm this issue on Python 2.7 and that the provided fix in the comments section works.

**Comment by spyoungtech** [comment]
Also encountered this issue. The suggestion by @taylorsmurphy fixes the issue for me.

Any chance of getting this change merged in? Any concerns or blockers to this?

**Comment by boppreh** [comment]
Hi @spyoungtech 

taylorsmurphy's suggestion hardcodes the type to long long, which may not be correct.

The master branch should contain a fixed due to the related problems reported and fixed by #186. Can you check that the master branch works for you>

**Comment by spyoungtech** [comment]
Thanks for the speedy reply @boppreh -- I can confirm that using the master branch fixes the issue as well 👍
