### ISSUE TITLE
Mac OS X python 2.7.15 AttributeError: 'module' object has no attribute 'map_name'

### ISSUE THREAD

**Issue by jsolderitsch** [boppreh/keyboard#165]
I have a third party python program that imports keyboard.

I did a pip install keyboard and when I saw a Quartz dependency error, I did a pip install pyobc.

When the program wants to receive a key press from me I get:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/keyboard/_darwinkeyboard.py", line 371, in run
    Quartz.CFRunLoopRunInMode(Quartz.kCFRunLoopDefaultMode, 5, False)
  File "/usr/local/lib/python2.7/site-packages/keyboard/_darwinkeyboard.py", line 400, in handler
    self.callback(KeyboardEvent(event_type, scan_code, name=key_name, is_keypad=is_keypad))
  File "/usr/local/lib/python2.7/site-packages/keyboard/__init__.py", line 251, in direct_callback
    if is_modifier(event.scan_code): self.active_modifiers.add(event.scan_code)
  File "/usr/local/lib/python2.7/site-packages/keyboard/__init__.py", line 142, in is_modifier
    _modifier_scan_codes.update(*scan_codes)
  File "/usr/local/lib/python2.7/site-packages/keyboard/__init__.py", line 141, in <genexpr>
    scan_codes = (key_to_scan_codes(name, False) for name in all_modifiers)
  File "/usr/local/lib/python2.7/site-packages/keyboard/__init__.py", line 319, in key_to_scan_codes
    t = tuple(_collections.OrderedDict((scan_code, True) for scan_code, modifier in _os_keyboard.map_name(normalized)))
AttributeError: 'module' object has no attribute 'map_name'
```

This same program works apparently for windows users.

**Comment by JoffreyPoreeCoding** [comment]
Same issue here..

**Comment by jsolderitsch** [comment]
Thanks for the confirmation -- not just me then.

**Comment by shpigunov** [comment]
Can confirm. 

The issue persists in macOS 10.13.4.

**System info:**
`Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64`
`Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin`
`keyboard 0.13.1`

**Error message:**
`...
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keyboard/__init__.py", line 642, in add_hotkey
    steps = parse_hotkey_combinations(hotkey)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keyboard/__init__.py", line 574, in parse_hotkey_combinations
    return tuple(tuple(combine_step(step)) for step in parse_hotkey(hotkey))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keyboard/__init__.py", line 360, in parse_hotkey
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keyboard/__init__.py", line 360, in <genexpr>
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keyboard/__init__.py", line 313, in key_to_scan_codes
    left_scan_codes = key_to_scan_codes('left ' + normalized, False)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keyboard/__init__.py", line 319, in key_to_scan_codes
    t = tuple(_collections.OrderedDict((scan_code, True) for scan_code, modifier in _os_keyboard.map_name(normalized)))
AttributeError: module 'keyboard._darwinkeyboard' has no attribute 'map_name'`

**Comment by jsolderitsch** [comment]
So how do I use keyboard from source? I downloaded the master zip file and then ran setup.py install and things still don't work for me!!

**Comment by shpigunov** [comment]
The PyPI version is the same as the latest release.
Apparently, the fix will propagate after the next release?

**Comment by boppreh** [comment]
The fix is now available on version 0.13.2. Please try `pip install --upgrade keyboard` to use the latest version.

**Comment by jsolderitsch** [comment]
For me, this release fixes the problem and I am able to use the third-party application that uses keyboard successfully. Thanks for the fix!!
