### ISSUE TITLE
How to Properly Exit Script

### ISSUE THREAD

**Issue by Apollys** [boppreh/keyboard#167]
I've been noticing my scripts rarely exit correctly if I try to use `sys.exit()`, for example:

```python
import sys
import keyboard

def callback():
   print('Callback')
   sys.exit()

SCAN_CODES = {'LEFT_CONTROL' : 29, 'LEFT_SHIFT': 42, 'A' : 30}

def main():
   keyboard.add_hotkey((29, 42, 30), callback, (), False, .5)
   keyboard.wait()

main()
```
gives me the following output

```
Callback
Traceback (most recent call last):
  File "scancodetest.py", line 15, in <module>
    main()
  File "scancodetest.py", line 13, in main
    keyboard.wait()
  File "C:\ProgramData\Anaconda3\lib\site-packages\keyboard\__init__.py", line 881, in wait
    _time.sleep(1e6)
KeyboardInterrupt
```
I launched the script, pressed the corresponding hotkey combination, and immediately saw 'Callback' output to the terminal.  I waited ~5 seconds or so and the script still didn't exit.  I suspect I may have exited the thread corresponding to the callback, but not the full application.

**Comment by shpigunov** [comment]
I normally add an exit hotkey like: `keyboard.wait("ctrl+shift+x")`.
Alternatively, you could wait for your exit hotkey with `keyboard.wait()` and perform the rest of the logic.

**Comment by provinzkraut** [comment]
I think it should possible to exit execution at any time with `exit()` or by raising `SystemExit` directly.
Not being able to do so seems to be quite the drawback and it should at least be documented properly that these won't behave as expected.

I'm currently having some trouble solving a situation where I now need to call `os._exit(0)`, but this isn't triggering functions registered using `atexit.register`, so I manually need to perform some actions before.

**Comment by provinzkraut** [comment]
The problem could be solved by replacing [keyboard.wait](https://github.com/boppreh/keyboard/blob/master/keyboard/__init__.py#L874) with something like this:

```
class _Wait:
    """
    Blocks the program execution until the given hotkey is pressed or,
    if given no parameters, blocks until `stop` is called.
    """
    def __init__(self):
        self._lock = _Event()

    def __call__(self, hotkey=None, suppress=False, trigger_on_release=False):
        if hotkey:
            remove = add_hotkey(hotkey, lambda: self._lock.set(), suppress=suppress, trigger_on_release=trigger_on_release)
            self._lock.wait()
            remove_hotkey(remove)
        else:
            self._lock.wait()

    def stop(self):
        self._lock.set()


wait = _Wait()
```

This would maintain backwards compatibility and add the ability to release the lock manually by calling `keyboard.wait.stop()`.
