### ISSUE TITLE
cygwin support

### ISSUE THREAD

**Issue by Eeems** [boppreh/keyboard#181]
If I try to use keyboard inside a [cygwin](http://www.cygwin.com/) console I get the following error:
```
Traceback (most recent call last):
  File "./ManageDB.py", line 7, in <module>
    import keyboard
  File "/usr/lib/python2.7/site-packages/keyboard/__init__.py", line 126, in <module>
    raise OSError("Unsupported platform '{}'".format(_platform.system()))
OSError: Unsupported platform 'CYGWIN_NT-10.0'
```
I would expect that either the linux or windows keyboard support would also work with cygwin.

**Comment by boppreh** [comment]
Hi Eeems

Sorry for not answering, I had to be away for a while.

The library did not recognize the platform name, but you try forcing module tests for the Windows and Linux backends:

```
python -m keyboard._nixkeyboard
python -m keyboard._winkeyboard
```

If one of them finishes loads without error you can change the [code that decides which backend to load](https://github.com/boppreh/keyboard/blob/f23d1f29302c673a138929f1e243c79958870c51/keyboard/__init__.py#L118). Let me know if either works and I'll apply the patch.

**Comment by Eeems** [comment]
Running either of those will trigger an Unsupported platform error. After tweaking __init__.py I recieved an error about not being root for _nixkeyboard and `ValueError: _type_ 'v' not supported` when trying to use _winkeyboard (failed ctypes import).

It looks like a little work is still needed to get this working.

**Comment by Lucas-C** [comment]
Same for me :
```
lucas_cimon@L-5CD7115LJ8{}[master]():python 1$ python3 -m keyboard._winkeyboard
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/keyboard/_winkeyboard.py", line 33, in <module>
    from ctypes.wintypes import WORD, DWORD, BOOL, HHOOK, MSG, LPWSTR, WCHAR, WPARAM, LPARAM, LONG, HMODULE, LPCWSTR, HINSTANCE, HWND
  File "/usr/lib/python3.7/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported
lucas_cimon@L-5CD7115LJ8{}[master]():python 1$ python3 -m keyboard._nixkeyboard
/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'keyboard._nixkeyboard' found in sys.modules after import of package 'keyboard', but prior to execution of 'keyboard._nixkeyboard'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/keyboard/_nixkeyboard.py", line 183, in <module>
    listen(p)
  File "/usr/lib/python3.7/site-packages/keyboard/_nixkeyboard.py", line 119, in listen
    build_device()
  File "/usr/lib/python3.7/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/usr/lib/python3.7/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.
```
