### ISSUE TITLE
Overflowerror with Python 3.7 on Windows

### ISSUE THREAD

**Issue by Aran-Fey** [boppreh/keyboard#186]
The `add_hotkey` function doesn't work on Windows with Python 3.7 (64-bit):

```
import keyboard, time

keyboard.add_hotkey('a', print)

time.sleep(5)
```

The traceback:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python37\lib\site-packages\keyboard\__init__.py", line 292, in listen
    _os_keyboard.listen(self.direct_callback)
  File "C:\Python37\lib\site-packages\keyboard\_winkeyboard.py", line 560, in listen
    prepare_intercept(callback)
  File "C:\Python37\lib\site-packages\keyboard\_winkeyboard.py", line 553, in prepare_intercept
    keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL)
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert
```

**Comment by Farm-Art** [comment]
Not just the hotkeys, any attempt to create a hook fails.

**Comment by Giahieu** [comment]
same here

**Comment by boppreh** [comment]
I've improved the Win32 calls and it has fixed the problem in my system. Can you check on your side?

**Comment by Aran-Fey** [comment]
Sorry for the late response. The latest version on the master branch does indeed work as expected now. Thanks for the fix!

**Comment by majj** [comment]
it's still there for master branch with python 3.7 on Windows 64 bits

**Comment by GeorgeSp1** [comment]
Same with @lkingscott, I just tried this:
```
def stop():
	while True:#making a loop
	    if k.is_pressed('q'):#if key 'q' is pressed 
	        print('You Pressed A Key!')
	        global stop 
	        stop = True
	        break#finishing the loop
	    else:
	        pass

```
and i got

> Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\site-packages\keyboard\__init__.py", line 292, in listen
    _os_keyboard.listen(self.direct_callback)
  File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\site-packages\keyboard\_winkeyboard.py", line 560, in listen
    prepare_intercept(callback)
  File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\site-packages\keyboard\_winkeyboard.py", line 553, in prepare_intercept
    keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL)
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert

on windows10 64bit with python 3.7

**Comment by lkingscott** [comment]
> Same with @lkingscott, I just tried this:
> 
> ```
> def stop():
> 	while True:#making a loop
> 	    if k.is_pressed('q'):#if key 'q' is pressed 
> 	        print('You Pressed A Key!')
> 	        global stop 
> 	        stop = True
> 	        break#finishing the loop
> 	    else:
> 	        pass
> ```
> and i got
> 
> > Exception in thread Thread-2:
> > Traceback (most recent call last):
> > File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
> > self.run()
> > File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
> > self._target(*self._args, **self._kwargs)
> > File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\site-packages\keyboard__init__.py", line 292, in listen
> > _os_keyboard.listen(self.direct_callback)
> > File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\site-packages\keyboard_winkeyboard.py", line 560, in listen
> > prepare_intercept(callback)
> > File "C:\Users\George\AppData\Local\Programs\Python\Python37\lib\site-packages\keyboard_winkeyboard.py", line 553, in prepare_intercept
> > keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL)
> > ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert
> 
> on windows10 64bit with python 3.7

Downgraded to Python 3.6.5 64 bit and problem goes away.

**Comment by Igli2** [comment]
My problem is a bit more complicated...
I wrote a program, where you can select a hotkey, using the method keyboard.read_key()
Then I compiled the program with cx_Freeze. Everything worked fine, but when I started the program an error occured:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\keyboard\__init__.py", line 292, in listen
    _os_keyboard.listen(self.direct_callback)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\keyboard\_winkeyboard.py", line 560, in listen
    prepare_intercept(callback)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python36\lib\site-packages\keyboard\_winkeyboard.py", line 553, in prepare_intercept
    keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL)
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert
```

The exception was thrown when the line "pressed_key = keyboard.read_key()" was executed. I put a print statement ahead of the line and after this line. Only the first one was printed.

**Comment by muhammeteminturgut** [comment]
> I am also having this issue with python3.7 on windows 10.

Same here.

**Comment by MrZog-TheDev** [comment]
I m also having this issue with python3.7 and windows 10.
Quick and dirty fix: removing the call to ```GetModuleHandleW``` seems to work for my simple use case.

```
_winkeyboard.py line 553:
SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL) -> SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, NULL, NULL)
```

**Comment by Igli2** [comment]
Thank You :) This helped me a lot!

**Comment by chrisddr77** [comment]
This also fixed the issue for me with Python3.7 and Windows 10 64Bit! Thank you!
