### ISSUE TITLE
OSError: exception: access violation reading 0x00000004

### ISSUE THREAD

**Issue by GlassGruber** [boppreh/keyboard#196]
Hey there!
I'm trying to create a simple tool (I think) that should help me with a bunch of manual copy/paste operations.

Basically I want to run a script every time I copy some text I've selected. This is my very first try to see if it could work

```python
import keyboard as k
from tkinter import Tk

def print_clip():
    t = Tk()
    t.withdraw()
    clip = t.clipboard_get() 
    print(f'Clipped: "{clip}"')
    t.destroy()

k.add_hotkey('ctrl+c, ctrl+c', print_clip, suppress=True, trigger_on_release=True)
k.wait()
```

It kinda works, but I got back this error that will break the script. 
````
Clipped: "Copy this string"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "[REDACTED_PYTHON_PATH]\Lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "[REDACTED_PYTHON_PATH]\Lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "[REDACTED_VIRTUALENV_PATH]\lib\site-packages\keyboard\__init__.py", line 292, in listen
    _os_keyboard.listen(self.direct_callback)
  File "[REDACTED_VIRTUALENV_PATH]\lib\site-packages\keyboard\_winkeyboard.py", line 562, in listen
    while not GetMessage(msg, NULL, NULL, NULL):
OSError: exception: access violation reading 0x00000004
````

Unfortunately I'm quite a novice, maybe I'm trying to do something funky and I'm overlooking something obvious. I'm on a Windows 7 machine with Python 3.7

Thank you for any suggestion!

**Comment by boppreh** [comment]
Hi @GlassGruber 

That's a strange issue. If possible, I have two questions:

- Is your setup unusual in some way? Running in a virtual machine, emulated devices, etc?
- Can you try the version in the master branch? It has several fixes related to low level Windows functions.

**Comment by GlassGruber** [comment]
> Can you try the version in the master branch? It has several fixes related to low level Windows functions.

Nice! As far as I can tell with my simple tests the master branch works without issues! :+1: 

Thank you for your time!
