### ISSUE TITLE
keyboard.wait() crash on windows10 /anaconda

### ISSUE THREAD

**Issue by ks00x** [boppreh/keyboard#237]
just did a fresh install of anaconda (most recent). The keyboard.wait() stuff throws an exception. Triggering keypresses works though. version 0.13.02 . Maybe a reappearance of [https://github.com/boppreh/keyboard/issues/80](url)  ?

`Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyboard
>>> keyboard.wait('esc')
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\develop\anaconda\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\develop\anaconda\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\develop\anaconda\lib\site-packages\keyboard\__init__.py", line 292, in listen
    _os_keyboard.listen(self.direct_callback)
  File "C:\develop\anaconda\lib\site-packages\keyboard\_winkeyboard.py", line 560, in listen
    prepare_intercept(callback)
  File "C:\develop\anaconda\lib\site-packages\keyboard\_winkeyboard.py", line 553, in prepare_intercept
    keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL)
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert`

**Comment by Lv-L** [comment]
I've got the same issue, Windows 10, Python 3. 

`Traceback (most recent call last):
  File "C:\Users\117755\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\117755\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\117755\OneDrive - TGS Kew\Projects\Python\Python 3\Keyboard\keyboard\__init__.py", line 296, in listen
    _os_keyboard.listen(self.direct_callback)
  File "C:\Users\117755\OneDrive - TGS Kew\Projects\Python\Python 3\Keyboard\keyboard\_winkeyboard.py", line 560, in listen
    prepare_intercept(callback)
  File "C:\Users\117755\OneDrive - TGS Kew\Projects\Python\Python 3\Keyboard\keyboard\_winkeyboard.py", line 553, in prepare_intercept
    keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL)
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert`

**Comment by Lv-L** [comment]
Same issue W/ Windows 10 and Python 3.

**Comment by rtaib** [comment]
Same issue on Win10, Python 3.7 (Anaconda) for the `hook()` method, making the whole package unable to detect any key press.

**Comment by Lv-L** [comment]
Works after rolling back. definitely an issue with the latest version.

**Comment by ks00x** [comment]
pip install keyboard==0.11.0 
is the latest that works for me!
