### ISSUE TITLE
keyboard.add_word_listener fails to work with ":" symbol / Sca

### ISSUE THREAD

**Issue by xazw** [boppreh/keyboard#240]
1. Consider code meant to abbreviate dates, where typing 'dd1' will output date and time. See 5 variations thereof what is _intended_:

    - Press 'dd1' - 2019-02-08 00:02:02
    - Press 'dd2' - 08.02.2019
    - Press 'dd3' - 00:02:02
    - Press 'dd4' - 20190208-021743
    - Press 'dd5' - 20190208021744

2. The simple code meant to produce the above is this:

    ```python
    import keyboard
    import datetime as dt
    import time

    def AddDateTimeCommand():
        keyboard.write(dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S") )

    def AddDateCommand():
        keyboard.write(dt.date.today().strftime("%d.%m.%Y") )

    def AddTimeCommand():
        keyboard.write(dt.datetime.now().strftime("%H:%M") )

    def AddDatetimeIdCommand():
        keyboard.write(dt.datetime.now().strftime("%Y%m%d-%H%M%S") )

    def AddDatetimeIdJoinedCommand():
        keyboard.write(dt.datetime.now().strftime("%Y%m%d%H%M%S") )


    abbrevs = [
        ("dd1", AddDateTimeCommand),
        ("dd2", AddDateCommand),
        ("dd3", AddTimeCommand),
        ("dd4", AddDatetimeIdCommand),
        ("dd5", AddDatetimeIdJoinedCommand),
    ]

    for abr in abbrevs:
        keyboard.add_word_listener(abr[0], abr[1], triggers=['space'], match_suffix=False, timeout=2)

    while True:
        time.sleep(1)
    ```

3. However, the code instead outputs the following:

    - Press 'dd1' - 2019-02-0802
    - Press 'dd2' - 08.02.2019
    - Press 'dd3' - 00
    - Press 'dd4' - 20190208-021743
    - Press 'dd5' - 20190208021744

4. From the above: only outputs for 'dd2', 'dd4' and 'dd5' are correct. 'dd1' and 'dd4' fails.

5. My suspicion is that it fails at the colon symbol ":", or in the 'space' symbol. In addition, and as this may be helpful, the failing code outputs as follows:

    Traceback (most recent call last):
      File "/home/xazw/.local/lib/python3.6/site-packages/keyboard/_generic.py", line 22, in invoke_handlers
        if handler(event):
      File "/home/xazw/.local/lib/python3.6/site-packages/keyboard/__init__.py", line 1106, in handler
        callback()
      File "./testkey.py", line 75, in AddDateTimeCommand
        keyboard.write(dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S") )
      File "/home/xazw/.local/lib/python3.6/site-packages/keyboard/__init__.py", line 852, in write
        scan_code, modifiers = next(iter(entries))
    StopIteration

    Traceback (most recent call last):
      File "/home/xazw/.local/lib/python3.6/site-packages/keyboard/_generic.py", line 22, in invoke_handlers
        if handler(event):
      File "/home/xazw/.local/lib/python3.6/site-packages/keyboard/__init__.py", line 1106, in handler
        callback()
      File "./testkey.py", line 81, in AddTimeCommand
        keyboard.write(dt.datetime.now().strftime("%H:%M") )
      File "/home/xazw/.local/lib/python3.6/site-packages/keyboard/__init__.py", line 852, in write
        scan_code, modifiers = next(iter(entries))
    StopIteration
    ^CTraceback (most recent call last):
      File "./testkey.py", line 102, in <module>
        time.sleep(1)
    KeyboardInterrupt

What could be the issue?

**Comment by Dhairyashilvp** [comment]
I am facing Same problem with the write method in the keyboard package.
It breaks out with the following error for Symbol such as @, (, { ,: etc. 

File "/home/dhairyashilp/.local/lib/python3.6/site-packages/keyboard/__init__.py", line 854, in write
    scan_code, modifiers = next(iter(entries))
StopIteration

Please Let me know if there is any solution.
