### ISSUE TITLE
KeyError using 'win' modifier

### ISSUE THREAD

**Issue by wiiittttt** [boppreh/keyboard#25]
It looks like there is an issue in _keyboard_event.py with `canonical_names` mapping "win" to "windows". In the `to_scan_code` dictionary, there is only "left windows" and "right windows".

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\keyboard\_generic.py", line 23, in invoke_handlers
    if handler(event):
  File "C:\Python34\lib\site-packages\keyboard\__init__.py", line 255, in handler
    unexpected = not any(matches(event, part) for part in steps[state.step])
  File "C:\Python34\lib\site-packages\keyboard\__init__.py", line 255, in <genexpr>
    unexpected = not any(matches(event, part) for part in steps[state.step])
  File "C:\Python34\lib\site-packages\keyboard\__init__.py", line 132, in matches
    return matched_name or _os_keyboard.map_char(name)[0] == event.scan_code
  File "C:\Python34\lib\site-packages\keyboard\_winkeyboard.py", line 431, in map_char
    return -media_name_to_vk(name), []
  File "C:\Python34\lib\site-packages\keyboard\_winkeyboard.py", line 437, in media_name_to_vk
    raise ValueError('Key name {} is not mapped to any known key.'.format(repr(name)))
ValueError: Key name 'windows' is not mapped to any known key.
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\keyboard\_winkeyboard.py", line 428, in map_char
    scan_code, shift = to_scan_code[name]
KeyError: 'windows'

Code used:

`keyboard.add_hotkey('win+comma', lambda e: keyboard.send('volume down'))`

**Comment by boppreh** [comment]
Thanks, nice catch. Fixed in master.

By the way, hotkeys don't pass any arguments by default, so you should remove the `e` parameter from your lambda. If you want access to the underlying event use `hook(callback)` or `hook_key(key, callback)`.

**Comment by wiiittttt** [comment]
Great. Thanks.
