### ISSUE TITLE
key combination listening doesn't work on Linux 

### ISSUE THREAD

**Issue by redstoneleo** [boppreh/keyboard#270]
It seems key combination listening doesn't work on Linux(tested on Linux Mint)
`
keyboard.add_hotkey('Shift+F1', self.toggleTranslation)
`
caused the exception 

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mint/Documents/build/exe.linux-x86_64-3.6/lib/keyboard/_generic.py", line 58, in process
    if self.pre_process_event(event):
  File "/home/mint/Documents/build/exe.linux-x86_64-3.6/lib/keyboard/__init__.py", line 216, in pre_process_event
    callback(event)
  File "/home/mint/Documents/build/exe.linux-x86_64-3.6/lib/keyboard/__init__.py", line 647, in <lambda>
    handler = lambda e: (event_type == KEY_DOWN and e.event_type == KEY_UP and e.scan_code in _logically_pressed_keys) or (event_type == e.event_type and callback())
TypeError: <lambda>() missing 1 required positional argument: 'e'

```

**Comment by predragmandic** [comment]
This is because the callback that you used expects *self* as first argument. Keyboard calls it without arguments. Try implementing `toggleTranslation` without *self*.
