### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'dumpkeys'

### ISSUE THREAD

**Issue by SkyRalf** [boppreh/keyboard#292]
Hello,
I use the "keyboard Lib" on Windows  and Raspberry Pi-3 successfully.
Now I would like to use it on my "Volumio Sound Player" but  w/o success.
I have "Python-3.4" installed on that device (HW is a Raspberry Pi 2)

When I try to run your example: "pressed_keys.py" , I get the following Traceback message:

================= Console output==========================
root@volumio-2:/home/volumio# python3 pressed_keys.py
Traceback (most recent call last):
  File "pressed_keys.py", line 15, in <module>
    keyboard.hook(print_pressed_keys)
  File "/usr/local/lib/python3.4/dist-packages/keyboard/__init__.py", line 459, in hook
    append(callback)
  File "/usr/local/lib/python3.4/dist-packages/keyboard/_generic.py", line 67, in add_handler
    self.start_if_necessary()
  File "/usr/local/lib/python3.4/dist-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/usr/local/lib/python3.4/dist-packages/keyboard/__init__.py", line 194, in init
    _os_keyboard.init()
  File "/usr/local/lib/python3.4/dist-packages/keyboard/_nixkeyboard.py", line 114, in init
    build_tables()
  File "/usr/local/lib/python3.4/dist-packages/keyboard/_nixkeyboard.py", line 73, in build_tables
    dump = check_output(['dumpkeys', '--keys-only'], universal_newlines=True)
  File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'dumpkeys'

=============================================================
I tried to put a file with the name "dumpkeys" in different directories - > no luck.

I tried to re-install the "Keyboard Lib" with a dld zip file from Github and tried to run "setup"
-> no luck
Attempt to run setup.py:
error in keyboard setup command: 'install_requires' must be a string or list of strings containing valid prt specifiers

==========================================================
Question: What can I do to avoid "Error 2" 

Thank you very much for your advice

**Comment by boppreh** [comment]
[`dumpkeys`](http://man7.org/linux/man-pages/man1/dumpkeys.1.html) must be installed. I believe it comes from the "kdb" package. This is a bit of a strange problem, as this is the first Linux-based operating system that I see without this binary included. Can you post the result of `uname`?

**Comment by SkyRalf** [comment]
Dear "BoppreH",

thank you very much for your quick response. Indeed the "kbd" (not <kdb>)
package was missing. Had some issues installing it but now it works fine.
Without your help I would have been stuck.
Thanks again
Ralf


Am Mi., 25. Sept. 2019 um 07:01 Uhr schrieb BoppreH <
notifications@github.com>:

**Comment by georgettica** [comment]
same here, `dnf install kbd`
