### ISSUE TITLE
MacOS twice press(caps lock)  raise AttributeError

### ISSUE THREAD

**Issue by JMD110** [boppreh/keyboard#300]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jimengdie/spider/lib/python3.5/site-packages/keyboard/__init__.py", line 294, in listen
    _os_keyboard.listen(self.direct_callback)
  File "/Users/jimengdie/spider/lib/python3.5/site-packages/keyboard/_darwinkeyboard.py", line 431, in listen
    KeyEventListener(callback).run()
  File "/Users/jimengdie/spider/lib/python3.5/site-packages/keyboard/_darwinkeyboard.py", line 372, in run
    Quartz.CFRunLoopRunInMode(Quartz.kCFRunLoopDefaultMode, 5, False)
  File "/Users/jimengdie/spider/lib/python3.5/site-packages/keyboard/_darwinkeyboard.py", line 385, in handler
    if key_name.endswith("shift") and (flags & Quartz.kCGEventFlagMaskShift):
AttributeError: 'NoneType' object has no attribute 'endswith'

I just add "if key_name:" for pass the problem. I'm not sure whether change langudge input cause the problem.

**Comment by billgi1983** [comment]
I use the keyboard module on MacOS, and when I press 'Caps Lock', it will raise the same Error.
But if you disable 'Caps Lock' to switch language from Mac system settings, this error won't raise anymore.
I can't find a better solution at this moment.
