### ISSUE TITLE
How to run it inside Docker?

### ISSUE THREAD

**Issue by lalwanivikas** [boppreh/keyboard#334]
I want to run it inside docker, but I get following error message:

```
Couldn't get a file descriptor referring to the console
Traceback (most recent call last):
  File "./test1.py", line 5, in <module>
    keyboard.write('The quick brown fox jumps over the lazy dog.')
  File "/usr/local/lib/python3.8/site-packages/keyboard/__init__.py", line 854, in write
    scan_code, modifiers = next(iter(entries))
  File "/usr/local/lib/python3.8/site-packages/keyboard/_nixkeyboard.py", line 148, in map_name
    build_tables()
  File "/usr/local/lib/python3.8/site-packages/keyboard/_nixkeyboard.py", line 73, in build_tables
    dump = check_output(['dumpkeys', '--keys-only'], universal_newlines=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dumpkeys', '--keys-only']' returned non-zero exit status 1.
```

**My Dockerfile:**
```
FROM python:3
RUN apt-get update && apt-get install -y --no-install-recommends kmod kbd

ADD test1.py /

RUN pip install keyboard

CMD [ "python", "./test1.py" ]
```

**Test python script:**
```
import keyboard
import time

time.sleep(2)
keyboard.write('The quick brown fox jumps over the lazy dog.')
```

Any suggestions on fixing this?

**Comment by Raynman77** [comment]
I feel like I might be having a similar issue as @lalwanivikas . I can run a simple script on my workstation locally and it runs just fine, but if I import and initialize any keyboard functions in a script located on my local webserver, make the request to run the script, the script runs fine but none of the keyboard functions execute.

**Comment by alexkutsan** [comment]
I have the following error in docker : 
```
/usr/local/lib/python3.8/dist-packages/keyboard/_nixkeyboard.py:110: UserWarning: Failed to create a device file using `uinput` module. Sending of events may be limited or unavailable depending on plugged-in devices.
  device = aggregate_devices('kbd')
Exception in thread Thread-1:
Exception in thread Thread-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-4:
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_nixcommon.py", line 106, in start_reading
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.event_queue.put(device.read_event())
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_nixcommon.py", line 83, in read_event
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_nixcommon.py", line 106, in start_reading
    self.event_queue.put(device.read_event())
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_nixcommon.py", line 83, in read_event
    data = self.input_file.read(struct.calcsize(event_bin_format))
AttributeError: 'NoneType' object has no attribute 'read'
    self._target(*self._args, **self._kwargs)
    data = self.input_file.read(struct.calcsize(event_bin_format))
AttributeError: 'NoneType' object has no attribute 'read'
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_nixcommon.py", line 106, in start_reading
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.event_queue.put(device.read_event())
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_nixcommon.py", line 83, in read_event
    data = self.input_file.read(struct.calcsize(event_bin_format))
AttributeError: 'NoneType' object has no attribute 'read'
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_nixcommon.py", line 106, in start_reading
    self.event_queue.put(device.read_event())
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_nixcommon.py", line 83, in read_event
    data = self.input_file.read(struct.calcsize(event_bin_format))
AttributeError: 'NoneType' object has no attribute 'read'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 881, in wait
    remove = add_hotkey(hotkey, lambda: lock.set(), suppress=suppress, trigger_on_release=trigger_on_release)
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 639, in add_hotkey
    _listener.start_if_necessary()
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_nixkeyboard.py", line 114, in init
    build_tables()
  File "/usr/local/lib/python3.8/dist-packages/keyboard/_nixkeyboard.py", line 73, in build_tables
    dump = check_output(['dumpkeys', '--keys-only'], universal_newlines=True)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dumpkeys'
>>> 
developer@alex-WorkStation:/$ ^C
developer@alex-WorkStation:/$ ^C
developer@alex-WorkStation:/$ exit

```

**Comment by ArrayMy** [comment]
/usr/local/lib/python3.8/dist-packages/keyboard/_nixkeyboard.py:110: UserWarning: Failed to create a device file using `uinput` module. Sending of events may be limited or unavailable depending on plugged-in devices.
  device = aggregate_devices('kbd')

**Comment by lahwaacz** [comment]
You need to start the docker container with `--privileged` in order for `dumpkeys` to work in the container.
