### ISSUE TITLE
keyboard.write() not working with all characters 

### ISSUE THREAD

**Issue by N-Ziermann** [boppreh/keyboard#343]
Tested on Linux (newest Version of Pop OS)

When the string I want to write using keyboard.write() contains characters like ">" I get the following error message:

>> keyboard.write(">")

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.7/dist-packages/keyboard/__init__.py", line 854, in write scan_code, modifiers = next(iter(entries))
StopIteration

**Comment by srujandeshpande** [comment]
I got this error when working with Ubuntu for every single character

**Comment by MeFealWo** [comment]
Take a look at Issue #211 may be the same problem.

**Comment by gavinkrezel** [comment]
So I've been looking through the code a bit and I found out that it actually uses the keys themselves being pressed rather than the ASCII that combinations of those keys creates (not sure if I explained that quite right, but I hope that's close enough). 

So this problem will not be fixed without either adding a way to show a sequence of characters within a string, kinda like:

`keyboard.write('^hello world^1')`

In this example, ^ would represent the shift key being pressed while the next character is also being pressed. This would have an identical output what you would expect `keyboard.write('Hello World!)` to output.

Alternatively you could go through the effort of mapping _every single key_ on the keyboard to have a capital interpretation as well, which I feel like would take much longer to implement...

I don't know, I might play around with this a bit in a Linux VM to just see what happens.
