### ISSUE TITLE
pip can't install keyvoard > 0.11 on win7 / python2.7

### ISSUE THREAD

**Issue by konserw** [boppreh/keyboard#346]
Hi!
Unfortunately I still have win7 + python2.7 machine, and recently I tried to install latest keyboard with pip. Installation failed and it looks like pip thinks that keyboard depends on OSX-only packages:

```
C:\Python27\Scripts>pip.exe install keyboard -U
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please
 upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop s
upport for Python 2.7 in January 2021. More details about Python 2 support in pi
p, can be found at https://pip.pypa.io/en/latest/development/release-process/#py
thon-2-support
Looking in indexes: http://ukcamspypi.cam.newnhamgroup.com:8080/simple
Processing c:\users\builduser.newnhamsbs\appdata\local\pip\cache\wheels\f3\9d\8a
\2711e89f4ad001bd3f2c8e782fbb1120e90c2ac4354a5588e8\keyboard-0.13.5-cp27-none-an
y.whl
Collecting pyobjc
  Using cached pyobjc-5.3-py2-none-any.whl (2.7 kB)
Collecting pyobjc-framework-DiscRecording==5.3
  Using cached pyobjc-framework-DiscRecording-5.3.tar.gz (63 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python27\python.exe' -c 'import sys, setuptools, tokenize; sys
.argv[0] = '"'"'c:\\users\\buildu~1.new\\appdata\\local\\temp\\pip-install-_orlb
h\\pyobjc-framework-DiscRecording\\setup.py'"'"'; __file__='"'"'c:\\users\\build
u~1.new\\appdata\\local\\temp\\pip-install-_orlbh\\pyobjc-framework-DiscRecordin
g\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read
().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__,
'"'"'exec'"'"'))' egg_info --egg-base 'c:\users\buildu~1.new\appdata\local\temp\
pip-pip-egg-info-dogms3'
         cwd: c:\users\buildu~1.new\appdata\local\temp\pip-install-_orlbh\pyobjc
-framework-DiscRecording\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\buildu~1.new\appdata\local\temp\pip-install-_orlbh\pyobjc-f
ramework-DiscRecording\setup.py", line 32, in <module>
        if fn.startswith('_DiscRecording')
      File "pyobjc_setup.py", line 392, in Extension
        os_level = get_os_level()
      File "pyobjc_setup.py", line 206, in get_os_level
        pl = plistlib.readPlist('/System/Library/CoreServices/SystemVersion.plis
t')
      File "c:\python27\lib\plistlib.py", line 75, in readPlist
        pathOrFile = open(pathOrFile)
    IOError: [Errno 2] No such file or directory: '/System/Library/CoreServices/
SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
e logs for full command output.
```

In the end I've installed version 0.11 without problems - so I think it may be issue with your setup.py, not pip itself. 

I've also installed latest keyboard on win10 / python2.7 machine without problems, so it looks like it's not python 2.7 fault, but the os.

**Comment by konserw** [comment]
I've changed title as I've confirmed it is also reproducible on windows 8.1
