### ISSUE TITLE
use onrelease_key hook corretly clearly 

### ISSUE THREAD

**Issue by WingDust** [boppreh/keyboard#354]
I want to active that hotkey every times I pressed execute a function or callback

I try it's code
```python
import keyboard

def p():
    print('1')

keyboard.on_release_key('escape',p,suppress=False)

```

```
Traceback (most recent call last):
  File "E:\python\python3.8.1\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\python\python3.8.1\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\python3.8.1\lib\site-packages\keyboard\_generic.py", line 58, in process
    if self.pre_process_event(event):
  File "E:\python\python3.8.1\lib\site-packages\keyboard\__init__.py", line 213, in pre_process_event
    key_hook(event)
  File "E:\python\python3.8.1\lib\site-packages\keyboard\__init__.py", line 516, in <lambda>
    return hook_key(key, lambda e: e.event_type == KEY_DOWN or callback(e), suppress=suppress)
TypeError: p() takes 0 positional arguments but 1 was given

```

I don't how to use this function correctly , on_release_key and hook  should write what order,their relationship clearly

I check the issue
search look this code
```python
def printPressedKey(e):
print("key pressed	: {}".format(e.name))
keyboard.hook(printPressedKey)
keyboard.wait('esc',trigger_on_release=True)

```

I also try , it's not what i want , I want just listening one key don't need whole key
I need a correctly example

**Comment by WingDust** [comment]
forgive me for my shallowness i alse want to know the hook or on_release_key is run at one threading ,I use hotkey for multi threading

**Comment by WingDust** [comment]
I alway want to know have any to remove the remap key

**Comment by WingDust** [comment]
> 我一直想知道有什么要删除重映射键的
```python
keyboard.unhook_key('keyname')

```

**Comment by niktob560** [comment]
It's working, but you need to have one argument in the callback
```python
import keyboard

def printPressedKey(e):
    print("key pressed  : {}".format(e.name))
 
keyboard.on_release_key('win',printPressedKey,suppress=False)

while True:
    keyboard.wait('win')
```
