### ISSUE TITLE
output chinese in linux

### ISSUE THREAD

**Issue by kyzrong** [boppreh/keyboard#386]
in centos7x63,python3.6

```
#coding:utf-8
import keyboard
keyboard.write('中文')
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/keyboard/__init__.py", line 854, in write
    scan_code, modifiers = next(iter(entries))
StopIteration

the code run well in windows10,is there any solution?
thank you!

**Comment by gavinkrezel** [comment]
I have created a patch to fix this funny enough... I just cant figure out how to upload it lol

**Comment by gavinkrezel** [comment]
Alright, so weirdly enough the pip install keyboard command installs an outdated version of this where there is a bug that shows up. If you would like to fix this, you can either download it directly from GitHub and just put the folder where pip would usually install packages, or you can go into `__init__.py` and replace **line 855** with:

`except (KeyError, ValueError, StopIteration):`

This one line is what I spent literal hours today trying to find only to learn that the bug had already been fixed in the latest version. 😅

**Comment by gavinkrezel** [comment]
this should also fix #343 and #306.

**Comment by kyzrong** [comment]
yes , it solve my problem!
thank you so much!
(●’◡’●)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "boppreh/keyboard"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 上午10:50
收件人:&nbsp;"boppreh/keyboard"<keyboard@noreply.github.com&gt;;
抄送:&nbsp;"549311034"<kyzrong@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [boppreh/keyboard] output chinese in linux (#386)





 
this should also fix #343 and #306.

**Comment by ripnonfegames** [comment]
> Alright, so weirdly enough the pip install keyboard command installs an outdated version of this where there is a bug that shows up. If you would like to fix this, you can either download it directly from GitHub and just put the folder where pip would usually install packages, or you can go into `__init__.py` and replace **line 855** with:
> 
> `except (KeyError, ValueError, StopIteration):`
> 
> This one line is what I spent literal hours today trying to find only to learn that the bug had already been fixed in the latest version. 😅

Can't believe the fix is right here! Why does pip install keyboard install such and outdated version of this, though?
