### ISSUE TITLE
Error on keyboard.write with pipe( | )

### ISSUE THREAD

**Issue by dhsathiya** [boppreh/keyboard#389]
I have created a small Python utility by which I can use a keyboard as a macro keyboard.
https://github.com/dhsathiya/UMacro/

I am getting the following error in `keyboard.write` when I pass a pipe (`|`) sign as the argument.

The function I created: https://github.com/dhsathiya/UMacro/blob/master/umacro.py#L115

**Error**
```
Traceback (most recent call last):
  File "macro.py", line 198, in <module>
    main()
  File "macro.py", line 166, in main
    eval(function_name_call)
  File "<string>", line 1, in <module>
  File "macro.py", line 116, in typeto
    keyboard.write(cmd, delay=0, restore_state_after=True, exact=None)
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 860, in write
    press(modifier)
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 396, in press
    send(hotkey, True, False)
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 379, in send
    parsed = parse_hotkey(hotkey)
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 358, in parse_hotkey
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 358, in <genexpr>
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 324, in key_to_scan_codes
    raise ValueError('Key {} is not mapped to any known key.'.format(repr(key)), e)
ValueError: ("Key 'alt gr' is not mapped to any known key.", None)
```

**Keyboard Layout:** English(US)
**OS:** Ubuntu 20.04

**What I have tried**

1. Tried `str()` before passing the value to the function.
2. Multiple devices.
3. Multiple strings.
4. Works fine without pipe.
5. Works fine if I just `print`.

**Notes**
- The aim is to use the following string to be typed: `docker container ls | grep`
- Let me know if you want any more details for the following or want to test which other characters are not working.

**Comment by dhsathiya** [comment]
Closing as the issue is already present at https://github.com/boppreh/keyboard/issues/343
