### ISSUE TITLE
No way to catch exceptions?

### ISSUE THREAD

**Issue by Rawing** [boppreh/keyboard#39]
I'm trying to register a global hotkey, and if that fails, ask the user if they want to abort or continue regardless. However, the add_hotkey function doesn't throw an exception. Instead, an exception is thrown in a different thread.

Example:

```
import keyboard

try:
    keyboard.add_hotkey('ctrl+select', print, args=('foo',))
except:
    print('ERROR')
else:
    print('SUCCESS')
```

Output:
```
SUCCESS
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/keyboard/__init__.py", line 114, in listen
    _os_keyboard.listen(self.queue)
  File "/usr/lib/python3.5/site-packages/keyboard/_nixkeyboard.py", line 111, in listen
    build_device()
  File "/usr/lib/python3.5/site-packages/keyboard/_nixkeyboard.py", line 105, in build_device
    ensure_root()
  File "/usr/lib/python3.5/site-packages/keyboard/_nixcommon.py", line 163, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.
```
This behaviour is undesirable for obvious reasons, and there doesn't seem to be a workaround.

**Comment by boppreh** [comment]
You're right, that is pretty bad. I didn't expect the import to be happening in another thread. Fixing now...

**Comment by boppreh** [comment]
The latest version should now throw errors on the main thread. Note that errors only happen when you try to use a function, not during import, otherwise testing tools and the documentation generation would fail.

**Comment by Rawing** [comment]
Works as expected now, thanks.

**Comment by boppreh** [comment]
Good to know. If you still experience any problems feel free to reopen the issue, create a new one, or send me an email.
