### ISSUE TITLE
Some capital letters do not work on Ubuntu/linux

### ISSUE THREAD

**Issue by jvellemans** [boppreh/keyboard#408]
When doing some testing, i noted that capital letter "D" and "P" where not supported for whatever reason.
Here is the error code throwed.

File "/lib/python3.8/site-packages/keyboard/__init__.py", line 855, in write
    scan_code, modifiers = next(iter(entries))

**Comment by AddisonG** [comment]
I'm getting the same - no capital letters work, and same with punctuation.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 854, in write
    scan_code, modifiers = next(iter(entries))
StopIteration
```

**Comment by tkossak** [comment]
same here on Manjaro :(

**Comment by Mte90** [comment]
Probably is a duplicate of https://github.com/boppreh/keyboard/issues/185
I did also a bug bounty on that
