### ISSUE TITLE
Can't write _(underscore)

### ISSUE THREAD

**Issue by jd-0001** [boppreh/keyboard#434]
I am struggling with writing underscore using `keyboard.write`. It throws below error:

```bash
Traceback (most recent call last):
  File "temp.py", line 3, in <module>
    keyboard.write("Trying to write underscore: _")
  File "/home/john/pylab/env_test/lib/python3.8/site-packages/keyboard/__init__.py", line 854, in write
    scan_code, modifiers = next(iter(entries))
StopIteration
```

Script Code:
```python
# File: temp.py

import keyboard

keyboard.write("Trying to write underscore: _")
```

**Comment by anderph** [comment]
I'm also having this issue

**Comment by gavinkrezel** [comment]
So if I remember correctly, Python has several special characters that are used for various things. I believe the underscore will return the previously calculated value, so inside the library somewhere it probably has some sort of problem with these kinds of characters. If it is using regular expressions (regex), all of these special characters are used as flags for identifying strings.

I am actually not at a computer right now so I have no way of testing this idea, but try using an escape character (\) in front of underscores or asterisks or etc.

**Comment by jd-0001** [comment]
Hi, @gavinkrezel I tried using `\` after your response but unfortunately, it didn't work.

```py
# File: temp.py

import keyboard

keyboard.write("Trying to write underscore: \_")
```

**Comment by gavinkrezel** [comment]
Eh it was worth a shot I guess.

You might also be able to format it as a raw string. I think you do that by adding an r in front of your string.

Ex.   r"\\no more special charac\\ters"

**Comment by jd-0001** [comment]
Using raw string isn't doing something as well. :laughing: 

I guess we shall wait till it gets fixed. :wink:

**Comment by anderph** [comment]
I'm having the same issues.

**Comment by lnfjobs** [comment]
Works on OSX Python3.8.6

**Comment by Sterver47** [comment]
I think someone has solved here it: [https://github.com/boppreh/keyboard/issues/485#issuecomment-1004688511](https://github.com/boppreh/keyboard/issues/485#issuecomment-1004688511)
