### ISSUE TITLE
keyboard write doesn't show anything

### ISSUE THREAD

**Issue by NobodyXu** [boppreh/keyboard#446]
When I run my script:

```
#!/usr/bin/env python3

import keyboard

keyboard.write('a')

keyboard.write('a')
```

as root in linux, nothing happened:

```
$ sudo ./keyboardPressSimulator.py
$
```

If I typed this in the python interpreter directly, then from the second `write`, the program is actually able to simulate key press:

```
$ sudo python3                     
Python 3.8.8 (default, Apr 23 2021, 11:49:15)                          
[Clang 11.1.0 ] on linux                                               
Type "help", "copyright", "credits" or "license" for more information. 
>>> import keyboard                                                    
>>> keyboard.write("h")                                                
>>> keyboard.write("h")                                                
>>> h                                                                  
Traceback (most recent call last):                                     
  File "<stdin>", line 1, in <module>                                  
NameError: name 'h' is not defined                                     
>>> keyboard.write("h")                                                
>>> h                                                                  
Traceback (most recent call last):                                     
  File "<stdin>", line 1, in <module>                                  
NameError: name 'h' is not defined                                     
>>>                                                                    
$                                  
```

## System info

os:

```
NAME=Gentoo                                   
ID=gentoo                                     
PRETTY_NAME="Gentoo/Linux"                    
ANSI_COLOR="1;32"                             
HOME_URL="https://www.gentoo.org/"            
SUPPORT_URL="https://www.gentoo.org/support/" 
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

Kernel:

```
Linux gentoo 5.11.16-gentoo #2 SMP Fri Apr 23 21:01:39 AEST 2021 x86_64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz GenuineIntel GNU/Linux                                                                     
```

interpreter:

```
cpython 3.8.8
```

package `keyboard` version:

```
0.13.5
```

**Comment by lnfjobs** [comment]
This all works for me on custom linuxOS between Ubunutu and Kali. 
I feel this is something to do with your setup. Try not using Cpython and just Python3 latest, see if that works first. Then start looking at the compiler for your desired version of Cpython and see if it is mangling something. 
Just something I would look at. Good luck!

**Comment by lieryan** [comment]
Yeah, I can reproduce this as well. What I found is that it seems that the first keypress in a script does not work and it takes a second after the first `keyboard.write()` to actually work and start sending keys correctly. 

So, this works:

```
import keyboard
import time

# initialize keyboard module
keyboard.press_and_release('alt')
time.sleep(0.1)

# now you can actually send something
keyboard.write('hello')
```

If you remove the `sleep()` or set a sleep time that's too short, then `keyboard` may skip the first few characters you `write()`. There's nothing special about pressing `alt`, but as long as you start simulating key press, the startup timer begins.

I'm guessing that `keyboard` was initializing its background threads in the first simulated key press, and it missed all the simulated key presses that's supposed to be happening during the thread initialization.

**Comment by NobodyXu** [comment]
> This all works for me on custom linuxOS between Ubunutu and Kali.
> I feel this is something to do with your setup. Try not using Cpython and just Python3 latest, see if that works first. Then start looking at the compiler for your desired version of Cpython and see if it is mangling something.
> Just something I would look at. Good luck!

Cpython is the name of the official implementation of python3, so I am indeed running python3.

**Comment by arainflake** [comment]
ive had the same issue on linux: manjaro i3 (arch derivitive).
as lieryan mentioned, it seemed to need to be initialized first. so i dug through the code to see what might be causing it. i couldnt find the source of the issue, but a suitable solution.

theres an internal init function that can be called
keyboard._os_keyboard.init()
following that with a short delay of 100ms appeared to work, without needing to send superfluous key-strokes.

it seems clunky to refrence internal functions outside of the module, so i added this bit of code inside the modules __init__.py just under where _os_keyboard is defined.
_os_keyboard.init()
_time.sleep(0.1)

ran my code again, and no issues; works as intended. though still needs testing on other systems. ill push changes to a new branch once i can figure out githubs new token sillyness
