### ISSUE TITLE
StopIteration error when using keyboard.write() with keys that aren't digits and lowercase?

### ISSUE THREAD

**Issue by AmeliaYeah** [boppreh/keyboard#485]
So, I'm making a python script with the keyboard module, and I wanted to make it write an email. The code was relatively straightforward: **keyboard.write('test@test.com')**. When I ran the command, everything worked fine up until it reached the "@" symbol, to which it produced a tk exception:

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/keyboard/__init__.py", line 854, in write
    scan_code, modifiers = next(iter(entries))
StopIteration**

I then opened up a python interpreter and went to investigate by using keyboard.write() with **string.printable**. Lo and behold, it still errored out, but it also errored out not just at a symbol but at any uppercase letter.

This seems to be a relatively new issue since I had this script for quite a while (around 2 weeks or so), and since I installed a different operating system I had to reinstall everything including the keyboard package.

**Comment by jp-x-g** [comment]
For all of those helpless internet wanderers, the issue is this: it doesn't do uppercase letters because keyboards don't have them. That is to say, there's no "A" key, there's just an "a" and a "shift" key. Per the documentation, you're supposed to do something like:
`keyboard.write("Barnacle Jim has a long face.", exact=True)`
which will force it to just send the string as Unicode. This actually worked, when I did it a few days ago -- but it's not working now, for reasons I can't understand, and all searches I've tried have landed me in sad little threads like this with people just as flummoxed as me. At any rate, maybe this will give you something to chew on.
