### ISSUE TITLE
report a few errors in key mappings and some notes on Alt-Gr / ctrl+alt 

### ISSUE THREAD

**Issue by stanpetit** [boppreh/keyboard#50]
Hi every one ! smart-useful-complete pure python ctypes project ! Wow !
Here are a few errors I got.
Your skills are definitely higher than mine, but here are a few notes, with "a fresh view". 
A few tunings, and you will _Hit mY keYbOarD_ !
Hope it helps.
Regards, Stanislas.

```
# THE FILE:

import keyboard
# version is recent keyboard-master, lundi 13 février 2017, 16:42:31
# console is the notepad++ python console, 
# an instance of scintilla editor, as any other editor buffer, supports print.
# This is a UTF-8-BOM, Windows file, on winxp sp3.

def end_bye():
    keyboard.unhook_all()
    console.write('keyboard.unhook_all')
    
# succes
keyboard.press_and_release('shift+s, space')
# succes
keyboard.write('The quick brown fox jumps over the lazy dog.')
# sucks
keyboard.add_hotkey('Space', lambda: console.write('space was pressed') )
# sucks
keyboard.wait('a')

# EOF

# THE ERRORS OUTPUT:

keyboard.add_hotkey('Space', print, args=['space was pressed'])
SyntaxError: invalid syntax      ^

    keyboard.add_hotkey('Space', lambda: print 'space was pressed' )
SyntaxError: invalid syntax                  ^


keyboard.wait('a')
Traceback (most recent call last):
  File "...\hk\keyboard_test.py", line 36, in <module>
    keyboard.wait('a')
  File "C:\Python27\lib\site-packages\keyboard\__init__.py", line 652, in wait
    wait()
  File "C:\Python27\lib\site-packages\keyboard\__init__.py", line 639, in wait
    return q.get(timeout=1)
  File "C:\Python27\Lib\Queue.py", line 177, in get
    self.not_empty.wait(remaining)
  File "C:\Python27\Lib\threading.py", line 355, in wait
    remaining = endtime - _time()
KeyboardInterrupt
```
the script has properly stopped running,
but has printed "€€" , once at the caret position at which the script was launched, and then randomly through several other opened files in the notepad++ editor ... all along the same error.
 [let's talk about "€" later ...](#about-alternate-engraving)
### note: 
Maybe I am wrong in the way I watch the topic following : didn't dig your code enough yet.
Whatever, it sounds weird, and I am curious about the boolean's usage :
```
in: _winkeyboard.py, from_virtual_key{}:

with    0x41: ('a', False),           MOD_SHIFT=False ?
        0x30: ('0', False),   true    MOD_SHIFT=False ( ? or VK_NUMLOCK=False ? )
if      0x60: ('0', True) ,   true    MOD_SHIFT=True  ( ? or what else can be ? )
        0x6b: ('+', False),   is logic_true : char '+' is not a shifted one.
but     0xbb: ('+', False),   is representation_false in the vkKeyScan view
   -->  0xbb: ('=', False),   true
   -->  0xbb: ('+', True ),   true : '+' is ('shift', '='),
SEE:    0xbb: ('=', False),   doesn`t seem to exist in the dictionnary,
                              to be mapped to : _keyboard_event.py :
                              canonical_names = { ..., 'equal': '=', ... }
```
Though, it seems difficult to hold both ```0xbb:('=',False)```  and  ```0xbb:('+',True)```, in the same dictionary on the same key... , what it should definitely be in the vkKeyScan view, _if I don't have a completely wrong view of that topic_. Please forget and forgive the confusion if it is the case...
Would it mean that you would also exclude:
```
                '''&é"'(-è_çà)=''' and $ friends ?
              ( '''1234567890°+''',    £ flavour )
```
### also:
in: _keyboard_event.py :
```
    canonical_names = { ...,
                     'num add': '+',
                     'num plus': '+',
                     'num minus': '+',       # oops
                     'num sub': '-' , 
```

also, ```0xa2: ('left ctrl', False)``` ... are very ambiguous to me : the ctrl keys shifted do **not** produce anything in fact, their only _real context of life_ is the MOD_CONTROL + MOD_SHIFT flag of a vkKeyScan ! 
I guess that your mapping is including these cases as to compact data. 

Other implementation use this k:v on a different purpose: watch for the ```alt-key-pressed``` state of a key, in the case of UI menus handling with a &MenuItem shortcut mapping.

There is an implementation of these crossed mappings between vk and ascii 
representation in the "PythonWin" [source code on github](https://github.com/ksmyth/pywin32/blob/master/Pythonwin/pywin/scintilla/keycodes.py),[and a shorter version too](http://www.math.uiuc.edu/~gfrancis/illimath/windows/aszgard_mini/pylibs/pythonwin/pywin/scintilla/keycodes.py) with fewer mappings.

Yet their mapping is incomplete, as it has a contextual purpose.
Yours aims to be wider, so nice !

Their logic is to parse vk as``` "ascii_not_shifted +-" (+-shifted) ```to be sure to end with no ambiguity (function _parse_key_name(name)_).
Ex: outputs of test2() in keycodes.py:
```
    Alt+/  ->  191,19  ->  Shift+Alt+:           '/' is detected as 'shift'+':'
    \      ->   56,15  ->  Ctrl+Alt+_          it couldn't match an event as 'alt-gr'+'_' ...
```

Also it separates the users logic from the implementation logic : 
a silly example:
I want to set up a hk with the ``` '/' ``` symbol for my purpose, not the ``` ':' ``` symbol.
I think (hope) most people type``` 'shift+:' ```without the intent to press this specific combination, they do because "this is the way it is to get ``` '/' ``` ", from the _reptilian cognitive layer_, almost like walking.
Though, ```'ctrl+/'``` would be meaningful, ex. as an application hotkey, where the / holds the aim, however we do access to it. It is ```'shift+:'```, you know it, could you hold that for my higher-level-of-abstraction ... ? 
And this way, I am sure that both symbols will be available, as they **should not 
be mutually exclusive**, every char will be safe and glad to serve our most exquisite desires !

### About alternate engraving
the "alternate-engraving" key and WM_SYSKEYDOWN : 
```
in _winkeyboard.py,
         line~~300, ... alt_gr_scan_code = 541         # ???
         line~~121, WM_SYSKEYDOWN = 0x104 # Used for ALT key
         watch the results I get from a view on the events broadcasting :
         it is true for ( 'ctrl' , 'alt' , 'e' ), not for ( 'alt-gr' , 'e' ), on my winxp sp3
```
I don't see that as an _inconsistency_, just the complexity to be able to input more symbols than the number of keys we have on our keyboards. As the `alt` key served the UI menus fisrt, it is a way to have a kind of alternate-alt, that shares only a part of it's business with it's left sister, not as the `ctrl` and `shift` keys do, and usable with one finger only !!!
The more I used it, the more I loved that key. I was doing maths outside of latex : Autohothey was a big help to map _contextually_ all my keys to utf-8 Greek and math symbols on ``` alt-gr/ctrl+alt ``` ! 
Then giving the users two different methods of input, one for the left-handlers, one for the others ( 'alt-gr' | 'ctrl'+'alt' ) over-adds to the complexity.

By the way, your unicode implementation is a really consistent piece of code to study, as it is still a pain for me to have a large view on it, a really, really nice good help. 
Thanks a lot for the lesson .
```
VK_CONTROL   0x11
VK_MENU      0x12  :  alt     menu because it first gave access to menus, 
# note from WinUser.h :
# VK_L* & VK_R* - left and right Alt, Ctrl and Shift virtual keys.
# Used only as parameters to GetAsyncKeyState() and GetKeyState().
# No other API or message will distinguish left and right keys in this way.
#                     not so simple in fact ... alt-gr is the exception :
VK_LMENU     0xA4  :  alt
VK_RMENU     0xA5  :  alt-gr in the vk perspective, BUT NOT IN MESSAGING : 
                                    it gets broacasted as 'alt'+'mod_ctrl' 
                      and 'ctrl'+'mod_alt' yields the same result, as "€"
```
You can get a ?clear view of the mechanism in the exemples below: 
two ways to get the Euro symbol '€' ( bad news for me, European : some have "_the easy way_" to make some, and convert it to '$' or '£' as fast as they can, far away from my home, under some coconut-tree ... ;-). 
##### summary of the events sequence:
the details are [below_below](#below-below).
```
1)  typed ( 'alt-gr', 'e' )           2)  typed ( 'ctrl' , 'alt' , 'e' )
    event:                                event:
       kd  ctrl    NO MOD_KEY             syskd  MOD_KEY is VK_MENU 0x12, alt
       kd  alt     NO MOD_KEY                kd  ctrl    (+ mod_alt )
       kd  E                                 kd  E
       ch  €                                 ch  €
       ku  E                                 ku  E
    sysku  MOD_KEY is VK_CONTROL 0x11     sysku  MOD_KEY is VK_MENU 0x12, alt
       ku  alt     (+ mod_ctrl )             ku  ctrl    (+ mod_alt )
```

with a hotkeys dict like:
```
MOD_ALT     = 1 ;  MOD_CONTROL = 2
# key_k = 75                                   #  fires on:
my_hks = { 0 : ( 75, MOD_ALT             ),    #  'alt+k'
           1 : ( 75, MOD_ALT+MOD_CONTROL ) }   #  'ctrl+alt+k'  and  'alt-gr+k'
```
with hotkeys we don't care about checking the events details ... but it's far less powerful than what you are setting up on chars only, unicode included ! a blessing !

##### details:    1) pressing   ```( 'alt-gr', 'e' )```   to print the '€' euro sign :
```
<messages created-by="Winspector">                 <!-- 99.99% filtered ... -->
<message>
    <name>WM_KEYDOWN</name>
    <posted />
    <time>16:26:50.0468</time>
    <parameters>
        <parameter>Virtual Key: VK_CONTROL</parameter>  ctrl    NO MOD_KEY
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_KEYDOWN</name>                             
    <posted />                                          
    <time>16:26:50.0468</time>                          
    <parameters>                                        
        <parameter>Virtual Key: VK_MENU</parameter>     alt     NO MOD_KEY
    </parameters>                                       
</message>                                                      
<message>                                               
    <name>WM_KEYDOWN</name>                             
    <posted />                                          
    <time>16:26:50.0515</time>                          
    <parameters>                                        
        <parameter>Virtual Key: E</parameter>           E
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_CHAR</name>                                
    <posted />                                          
    <time>16:26:50.0515</time>                          
    <parameters>                                        
        <parameter>wParam: 0x000020ac</parameter>       €
        <parameter>lParam: 0x20120001</parameter>       
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_KEYUP</name>
    <posted />                                          
    <time>16:26:50.0718</time>                          
    <parameters>                                        
        <parameter>Virtual Key: E</parameter>           E
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_SYSKEYUP</name>                            
    <posted />                                          
    <time>16:26:51.0046</time>                          
    <parameters>                                        
        <parameter>wParam: 0x00000011</parameter>       MOD_KEY VK_CONTROL 0x11
        <parameter>lParam: 0xe01d0001</parameter>       ???
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_KEYUP</name>                               
    <posted />                                          
    <time>16:26:51.0046</time>                          
    <parameters>                                        
        <parameter>Virtual Key: VK_MENU</parameter>     alt (+ mod_ctrl )
    </parameters>                                       
</message>

```
##### details:    2) same money,  but using   ``` ( 'ctrl' , 'alt' , 'e' )```
```
<message>
    <name>WM_SYSKEYDOWN</name>
    <posted />
    <time>15:30:54.0406</time>
    <parameters>
        <parameter>wParam: 0x00000012</parameter>     MOD_KEY VK_MENU 0x12 alt
        <parameter>lParam: 0x20380001</parameter>       
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_KEYDOWN</name>                             
    <posted />                                          
    <time>15:30:54.0406</time>                          
    <parameters>                                        
        <parameter>Virtual Key: VK_CONTROL</parameter>  ctrl (+ mod_alt )
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_KEYDOWN</name>                             
    <posted />                                          
    <time>15:30:55.0046</time>                          
    <parameters>                                        
        <parameter>Virtual Key: E</parameter>           E
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_CHAR</name>                                
    <posted />                                          
    <time>15:30:55.0046</time>                 
    <parameters>                                        
        <parameter>wParam: 0x000020ac</parameter>       €
        <parameter>lParam: 0x20120001</parameter>       
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_KEYUP</name>                               
    <posted />                                          
    <time>15:30:55.0218</time>                          
    <parameters>                                        
        <parameter>Virtual Key: E</parameter>           E
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_SYSKEYUP</name>                            
    <posted />                                          
    <time>15:30:55.0328</time>                          
    <parameters>                                        
        <parameter>wParam: 0x00000012</parameter>     MOD_KEY VK_MENU 0x12 alt
        <parameter>lParam: 0xc0380001</parameter>       
    </parameters>                                       
</message>                                              
<message>                                               
    <name>WM_KEYUP</name>                               
    <posted />                                          
    <time>15:30:55.0328</time>                          
    <parameters>                                        
        <parameter>Virtual Key: VK_CONTROL</parameter>  ctrl (+ mod_alt )
    </parameters>
</message>

```
Winspector is freeware and very useful : select a window, rightckick the item
highlighted in the list, get "Messages"  -->  Messages_window: has an icon
"traffic light" : pauses events capture on/off, an icon "save" ... saves to xml.
Right click Messages_window, get "Edit message filter", kept event: right side.
It will filter the msgs outputs in the Messages_window, but it doesn`t apply
filter to the results in memory, and it saves all events it catches : events
captured during 3 key-press is already a big quantity of msgs, so, if you play 
with it, be sure to produce as few mouse moves and breathings as you can,
and be a good boy : mind the "traffic light", saving xml may hang for freeze !
```
# a quick filter script for the Large xml file :
import xml.etree.ElementTree as ET
file_in  = "messages3.xml"                  # same dir as script_file
file_out = "filtered_"+file_in
tree = ET.parse(file_in)                    # ASCII or use ET.XMLParser(enc...)
root = tree.getroot()
filter =  [ 'WM_SYSKEYDOWN' ,
            'WM_KEYDOWN'    ,
            'WM_CHAR'       ,
            'WM_KEYUP'      ,
            'WM_SYSKEYUP'   
            ]
for message in root.findall('message'):
    name = message.find('name').text
    if name not in filter:
        root.remove(message)
tree.write('filtered_messages.xml') # Result to an XML File

```
Once again, thank you for your this shared work and may the Force be with you ...

**Comment by boppreh** [comment]
Thank you for your input. I'm trying to answer as best as I can, but I had some trouble understand you at some points. If you think I misread something, please don't hesitate to point it out.

I have a feeling this was auto-translated somehow; if this is true, feel free to post in your native language. We may be lucky and share a common tongue, but otherwise it would help having the original version to verify the stranger sounding parts. If not, I'm very sorry and don't mean to offend, English is not my first language.

> keyboard.add_hotkey('Space', print, args=['space was pressed'])
> SyntaxError: invalid syntax      ^
> 
>     keyboard.add_hotkey('Space', lambda: print 'space was pressed' )
> SyntaxError: invalid syntax  

You are using Python 2, where `print` is an statement. I highly suggest switching to Python 3, but the library should still work in both versions, just not this specific example.

>  'num minus': '+',       # oops

Nice catch, thank you.

> And in: _winkeyboard.py, from_virtual_key={... 0xbb: ('=', False), doesn't seem to exist , mapped to :
> _keyboard_event.py canonical_names = { ..., 'equal': '=', ... } ?

The virtual key code is a table of values defined by Microsft (https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx) and there's no '=' key there.

> There is an implementation of these crossed mappings between vk and ascii
> representation in the "PythonWin" source code on github,and a shorter version too with fewer mappings.

That looks very useful, thank you. I'm not sure if VKs sufficient, specially for more unusual characters (e.g. what's the VK for `ç`?), but I think it could improve this library nonetheless.

>  I want to set up a hk with the '/' symbol for my purpose, not the ':' symbol.

Hotkeys in this library are shift-independent. It's a hot-**key**, not hot-**character**, after all, and adding a hotkey to `shift+:` should work instead of being silently impossible.

The Linux backend has very good support for mapping a combination of modifiers and a key to a specific character. I haven't found a similar solution in Windows, but I would love to get suggestions.

> I think (hope) most people type'shift+:'without the intent to press this specific combination, they do 
> because "this is the way it is to get '/' ", from the reptilian cognitive layer, almost like walking.
> Though, 'ctrl+/' would be meaningful, ex. as an application hotkey, where the / holds the aim, however > we do access to it. It is 'shift+:', you know it, could you hold that for my higher-level-of-abstraction ... ?
> And this way, I am sure that both symbols will be available, as they should not
> be mutually exclusive, every char will be safe and glad to serve our most exquisite desires !

Sorry, I re-read this paragraph multiple times and still can't understand the message. It would help if you specified what kind of layout you are using, because `:` in my layout is `shift+;`, and `/` is just `/`, without any modifiers. I also have no idea what you meant by `where the / holds the aim`. Could you please try rewording this?

> the "alternate-engraving" key and WM_SYSKEYDOWN :

I'm not sure I understand your confusion. Yes, the alt-gr scan code is arbitrary and hacky, but that value has been true in the Windows versions I tried so far, and I found no suitable constant from the official docs. The WM_SYSKEYDOWN is documented [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646286(v=vs.85).aspx).

> watch the results I get from a view on the events broadcasting :
> it is true for ( 'ctrl' , 'alt' , 'e' ), not for ( 'alt-gr' , 'e' ), on my winxp sp3

I didn't quite catch that. Could you elaborate?

And last, I'm not sure what you meant by the XML events. Are you reporting a problem, a suggestion, or something else?

**Comment by stanpetit** [comment]
Well you wouldn't expect to _share the same tongue_ with me, if you saw my teeth ... almost teeth of a saw ... ;-)
I am walking the wrench tongue and you are right : my brain is twisted, you are not the only one who tells me that I am writing an unbearable crap ... thanks for your patience.

I got it about my ` '/' vs 'shift+:' ` confusing stuff : it is parsed to its `scan_code,name,state`, exactly my _wish_!

About the `'alt-gr'` vs `'ctrl+alt'`, and the cumbersome msgs.xml extracts ( not xml events ! ): 
I am trying to point the difference of the events sequence produced by each of them (as I could see on my winxp sp3... with [Winspector](https://drive.google.com/open?id=0B5jB4ZMcLUkhWVZoWWJISmRaVDQ)) : in the users point of view, they mostly produce the same result, and I don't know many (Windows) application that offer to map a hotkey as a combination to  `'alt-gr'`, but any hotkey mapped on `'ctrl+alt'` will fire with `'alt-gr'` too. 

But if we look at the events sequences, they are not interpreted as the same combination of virtual keys. Now a summary of the summary of the previous post.
See below, the keydown events of each version:

```
                    events        vk        comment
( 'alt-gr', 'e' ) 
                  WM_KEYDOWN      ctrl      no modifier key
                  WM_KEYDOWN      alt       no modifier key
                         
( 'ctrl' , 'alt' , 'e' ) 
               WM_SYSKEYDOWN      alt       modifier key alt
                  WM_KEYDOWN      ctrl      ctrl + modifier key alt
```
                         
Now, you say that you are processing _hotkeys_, but nowhere I could see a `WM_HOTKEY` event expected ... or registered : ```user32.RegisterHotKey (None, id, modifiers, vk)```.

You are watching the `WM_KEYDOWN` and `WM_KEYUP` events and it also explains the way you slice each part of the key sequence in atomic chunks : you are (maybe) recomposing what can be ('ctrl'+'alt' will be recognized as a modifier) and get a scan_code from that. But in the case of `'alt-gr'` you need to rely on the ```alt_gr_scan_code = 541```, _WHICH DOESN'T REPRESENT A MODIFIER IN ITSELF_, but a numeric pointer to the _representation of the combination_ that is recognized as a modifier that _look ALMOST like_ `'ctrl'+'alt'`, and partially produces the same result, _PARTIALLY ONLY_ ...

```
MOD_NORM    = 0
MOD_ALT     = 1
MOD_CONTROL = 2
MOD_SHIFT   = 4
MOD_WIN     = 8
MOD_ALTGR   = 'sorry, no specific modifier key for me ! try to catch me as 
               MOD_ALT+MOD_CONTROL = 3, and also try MOD_CONTROL+MOD_ALT 
               but it still equals 3 ...'
```

Watching a sequence of WM_KEYDOWN/WM_KEYUP is not the same as watching a combination of vk+modifiers (aka `WM_HOTKEY`), and the difference between `'alt-gr'` and `'ctrl+alt'` vanishes in a `WM_HOTKEY` ... or details may be be contained in the `msg lParam`, some `VK_RMENU` for example... that I did not manage to extract yet.

When you point_out :
_winkeyboard.py,~378  ```# Pressing AltGr also triggers "right menu" quickly after.```
show me how to catch it, and you save my life !

Using `user32.RegisterHotKey()`, it is not possible to build a specific `alt-gr` hotkey, that wouldn't fire the same as `ctrl+alt`, as there is no specific modifier for the `alt-gr` key itself : 
it is treated as a combo of a slightly different nature compared to `ctrl+alt` combo.
And any hotkey I register with `'ctrl'+'alt'` will fire the same with `'alt-gr'`, it is precisely what I want to overcome ...
 And maybe you will need to dig this a little in regard to #48 ...

This is what I wanted to point, showing the _Winspector_ results (produced as an xml file) , and comparing them to [key-event-viewer](https://w3c.github.io/uievents/tools/key-event-viewer.html) shows the same differences ... in a different manner, as it shadows all the `WM_SYSKEYDOWN` events, not so reliable.

If I was stupid enough to give you an advise, I would say : " @boppreh ! try to register `WM_SYSKEYDOWN` and `WM_SYSKEYUP` events , and you will be safe with `'alt-gr'` ... " ! But I will try that myself before !

I care about all this because I am working on a little project, far less elaborated than yours, to handle an alternative hotkeys input in Notepad++(NPP) / PythonScript Plugin, Ctypes only, that should be portable to other python powered apps. I am over-crowded with nice formatting macros and scripts that I cannot use straight-away because of the hotkeys input limit of the ctrl alt shi(f)t mechanism. I am fed up twisting the fingers and as NPP saves its hotkeys mapping in an xml file, I will soon be able to remap some to my mechanism, and even map to my python scripts from an ini file, or so, by contextually overriding NPP hoykeys, as the python runs in NPP's thread !

Previously, I made an attempt with Autohotkey, but it was a kind of torture to compose the WinApi messages to send to the app from the outside. But AHK handles this very precisely, passing nicely into the thread of the app, obtained from its class name, window handle ...
And it sends hotkeys the way you do ... I don't yet manage this with python ...

Hence, there is definitely a difference of result. `WM_HOTKEY` events do not make any difference between alt-gr and ctrl+alt, even is they are different different combo ... that you are smart enough to catch !

I spent a whole day on your code : too smart for me. Everything is twisted inside the classes, no way get the roots mechanism of it ... and I am sorry to tell you that even :
```
import keyboard
def info(event):
    print (event.name + ", " + str(event.scan_code) + ", " + event.event_type)
keyboard.hook(info)
keyboard.wait("esc")
```
keeps waiting with no output at all ...


also:
```_winkeyboard.py, 347  # Sometimes two characters are written before the char we want,```
Try the "must-have" [BabelMap](http://www.babelstone.co.uk/Software/BabelMap.html) to explore Unicode hex representation of combining chars with dead_chars (diacritics) : the full Unicode standards guts for ... windows or [online](http://www.babelstone.co.uk/Unicode/babelmap.html).
And have a try to Winspector if you have a windows box! it hits any event. 

Best regards, Stanislas.

**Comment by stanpetit** [comment]
Hi BoppreH !

Nice to read your feedback, thanks. I will try to implement on your fix and
will tell you about.
I hope you dont expect this too soon ...

Best.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-25 18:21 GMT+01:00 BoppreH <notifications@github.com>:
