### ISSUE TITLE
when i try to get keys from chrome search input i get this error

### ISSUE THREAD

**Issue by kojibhy** [boppreh/keyboard#69]
Traceback (most recent call last):
  File "site-packages\keyboard\_generic.py", line 23, in invoke_handlers
  File "bin\modes.py", line 282, in data_event_json
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 96-100:
character maps to <undefined>

language: RU

**Comment by boppreh** [comment]
Hi kojibhy

Sorry taking so long to respond.

Can you post your code? My guess is that the library is return some Unicode string and your program assumes it's CP1252 (default encoding?).
